### ISSUE TITLE
怎么在NPM 上使用

### ISSUE THREAD

**Issue by gdzgshum** [suguangwen/vue-rolling#1]
import infiniteScroll from 'vue-infinite-scroll'
Vue.use(infiniteScroll)

换成你这个怎么使用呢？

**Comment by suguangwen** [comment]
还未上传到NPM ，现在的使用方式把文件下载下来，直接选中文件
import vue_scroll from './js/vue-scroll.js
Vue.use(vue_scroll)

**Comment by suguangwen** [comment]
已经上传到NPM
npm install vue_scroll --save

---

import vue_scroll from 'vue_scroll‘
Vue.use(vue_scroll)
这样使用就可以了
