### ISSUE TITLE
下拉过快的情况下可能会多次触发

### ISSUE THREAD

**Issue by zxnhl702** [suguangwen/vue-rolling#3]
前一次下拉加载的数据还没加载完  在滑动速度过快的情况下 会再短时间内多次触发加载  然后....页面数据就重复了.

额...请问有人碰到过这种情况吗

**Comment by suguangwen** [comment]
如果出现数据重复问题，不是插件的问题，应该是翻页出入栈代码写错了。

在源码中修改下面代码就可以设定触发时间，在你设定的时间内就不会重复触发滚动函数。
directive.scrollListener = throttle(directive.doCheck.bind(directive), 200)
这样修改就会1秒内不会重复触发下拉加载的函数。
directive.scrollListener = throttle(directive.doCheck.bind(directive), 1000)

**Comment by zxnhl702** [comment]
原来是这样  我自己的解决方法是设置一个变量 数据还在加载的时候设为false 这时候触发了直接return 

3Q
